"""Creacion de Fichas Tecnicas, enums y surtido rico

Revision ID: 7136f26870bf
Revises: 677780c6fdb5
Create Date: 2026-03-20 17:09:03.574051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7136f26870bf'
down_revision = '677780c6fdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ficha_tecnica_insumos',
    sa.Column('id_ficha_insumo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ficha_tecnica', sa.Integer(), nullable=False),
    sa.Column('id_mp', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Enum('CORTADO', 'DOBLILLADO', 'PESPUNTE', 'MONTADO', 'ADORNADO', name='etapaproduccion'), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('observacion_material', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_ficha_tecnica'], ['ficha_tecnica.id_ficha_tecnica'], ),
    sa.ForeignKeyConstraint(['id_mp'], ['materia_prima.id_mp'], ),
    sa.PrimaryKeyConstraint('id_ficha_insumo')
    )
    op.create_table('ficha_tecnica_procesos',
    sa.Column('id_proceso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ficha_tecnica', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Enum('CORTADO', 'DOBLILLADO', 'PESPUNTE', 'MONTADO', 'ADORNADO', name='etapaproduccion'), nullable=False),
    sa.Column('descripcion_instruccion', sa.Text(), nullable=False),
    sa.Column('maquinaria_sugerida', sa.String(length=100), nullable=True),
    sa.Column('observaciones_seguridad', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_ficha_tecnica'], ['ficha_tecnica.id_ficha_tecnica'], ),
    sa.PrimaryKeyConstraint('id_proceso')
    )
    op.drop_table('detalle_ficha_tecnica')
    with op.batch_alter_table('ficha_tecnica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_alta', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.drop_column('costo_unitario')

    with op.batch_alter_table('ficha_tecnica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estado')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('fecha_alta')

    op.create_table('detalle_ficha_tecnica',
    sa.Column('id_detalle_ft', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_ficha_tecnica', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_mp', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_requerida', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_ficha_tecnica'], ['ficha_tecnica.id_ficha_tecnica'], name=op.f('detalle_ficha_tecnica_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_mp'], ['materia_prima.id_mp'], name=op.f('detalle_ficha_tecnica_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_detalle_ft'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ficha_tecnica_procesos')
    op.drop_table('ficha_tecnica_insumos')
    # ### end Alembic commands ###
